### ISSUE TITLE
Question: is there any plans to support winston v3?

### ISSUE THREAD

**Issue by aledbf** [sparkida/winston-datadog#6]

**Comment by sparkida** [comment]
There is, I'll have an update soon!

**Comment by sparkida** [comment]
Just as a heads up, [Winston v3 has a major issue](https://github.com/winstonjs/winston/issues/1549#issuecomment-446279168) of mutating objects passed to it. This unexpected change would be problematic. Once the issue is patched, I'll get a release out.

**Comment by devilleweppenaar** [comment]
Thanks for all the effort on this @sparkida!

I see the referenced winston issue (winstonjs/winston#1549) was closed. Is this upgrade still blocked by breaking changes in winston 3?
